./openriscv_sopc_tb.v
../rtl/core/csr_regfile.v
../rtl/core/ctrl.v
../rtl/core/dff_lr.v
../rtl/core/div.v
../rtl/core/excp.v
../rtl/core/ex_ls.v
../rtl/core/exu.v
../rtl/core/id_ex.v
../rtl/core/idu.v
../rtl/core/if_ahb_interface.v
../rtl/core/if_id.v
../rtl/core/ifu.v
../rtl/core/ls_ahb_interface.v
../rtl/core/lsu.v
../rtl/core/ls_wb.v
../rtl/core/mul.v
../rtl/core/openriscv.v
../rtl/core/regfile.v
../rtl/interconnect/ahb3lite_pkg.sv
../rtl/interconnect/ahb3lite_interconnect_master_port.sv
../rtl/interconnect/ahb3lite_interconnect_slave_port.sv
../rtl/interconnect/ahb3lite_interconnect_slave_priority.sv
../rtl/interconnect/ahb3lite_interconnect.sv
../rtl/perip/ahb_sram/ahb_sram.v
../rtl/perip/ahb_sram/sram_8kx8.v
../rtl/sopc/openriscv_sopc.sv
../rtl/perip/ahb_uart/ahb_uart.v
../rtl/perip/ahb_uart/uart_rx.v
../rtl/perip/ahb_uart/uart_tx.v
../rtl/utils/async_fifo/async_long_to_short.v
../rtl/utils/async_fifo/async_short_to_long.v
../rtl/utils/async_fifo/async_fifo.v
../rtl/utils/async_fifo/b2g.v
../rtl/utils/async_fifo/dual_port_ram.v
../rtl/utils/async_fifo/g2b_core.v
../rtl/utils/async_fifo/re_con.v
../rtl/utils/async_fifo/wr_con.v
../rtl/utils/sync_fifo/sync_fifo.v
../rtl/perip/ahb_spi/ahb_spi.v
../rtl/perip/ahb_timer/ahb_timer.v
../rtl/perip/ahb_gpio/ahb_gpio.v
